// IF statements in javascript
let age = 25;
if (age>=18) {
    console.log("you are an adult");
}
else{
    console.log("you are a minor")
}
//boolean datatypes
let isstudent =true;
if(isstudent){
    console.log("you are a student");
}
else{
    console.log("you are not a student");
}
let Age =21;
if(Age>=18){
    console.log("you are old enough to drink");
}
    else if(Age>=100){
console.log("you are too old to drink alcohol");
    }
    else if("Age<0"){
        console.log("you are too young to drink alcohol");
    }
    else{
        console.log("you mus be 18+ to drink alcohol")
    }
    

